In [1]:
import numpy as np

In [4]:
#Create Array using numpy.empty(shape, dtype=float, order=’C’)

a=np.empty([3,3],dtype=int)
print("\n Matrix a: \n",a)




 Matrix a: 
 [[100670957509796               0 125462100637456]
 [125462100637536 125462100637616 125462100637696]
 [125462100637776 125462100637856              80]]


In [5]:
b=np.empty(3,dtype=int)
print("\n Matrix b: \n",b)


 Matrix b: 
 [24573315813           0         112]


In [6]:
#Create Array using numpy.empty(shape, dtype=None, order=’C’)

c=np.zeros([3,3],dtype=int)
print("\n Matrix c:\n",c)



 Matrix a:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [7]:
d=np.zeros([2,3],dtype=int)
print("\n Matrix d:\n",d)


 Matrix a:
 [[0 0 0]
 [0 0 0]]


In [8]:
e=np.zeros(3,dtype=int)
print("\n Matrix e:\n",e)


 Matrix e:
 [0 0 0]


# Operations on NumPy Arrays

## Arithmetic Operations

In [13]:
Tohru=np.array([1,2,3,4])

Honda=np.array([1,2,3,4])

Add1=Tohru+Honda
print(Add1)

[2 4 6 8]


In [14]:
Add2=np.add(Tohru, Honda)
print(Add2)

[2 4 6 8]


In [17]:
Kyo=np.array([1,2,3,4])
Add3=Tohru+Honda+Kyo
print(Add3)

[ 3  6  9 12]


In [18]:
Add4=np.add(Tohru, Honda, Kyo)
print(Add4)

[2 4 6 8]


## Substraction Operations


In [19]:
Yoki=np.array([10,8,6,4])
Akito=np.array([5,4,3,2])
Sub1=Yoki-Akito
print(Sub1)

[5 4 3 2]


In [21]:
Sub2=np.subtract(Yoki, Akito)
print(Sub2)

[5 4 3 2]


## Multiplication Operations

In [22]:
Shigure=np.array([10,20,30,40])
Hatori=np.array([10,20,30,40])
Mul1=Shigure*Hatori
print(Mul1)

[ 100  400  900 1600]


In [24]:
Mul2=np.multiply(Hatori,Shigure)
print(Mul2)

[ 100  400  900 1600]


## Division Operations

In [26]:
Saki=np.array([100,200,300,400])
Juki=np.array([5,6,7,8])
Div1=Saki/Juki
print(Div1)

[20.         33.33333333 42.85714286 50.        ]


In [27]:
Div2=np.divide(Saki, Juki)
print(Div2)

[20.         33.33333333 42.85714286 50.        ]


# Array Indexing

In [30]:
a=np.arange(10,1,-2)
print("\n A sequential array with a negative step: \n",a)

b=a[np.array([3,1,2])]
print("\n Elements at the indices are: \n",b)


 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at the indices are: 
 [4 8 6]


# Array Slicing

In [31]:
Arr=np.array([1,2,3,4,5,6,7])

print(Arr[1:5])

[2 3 4 5]


In [32]:
print(Arr[:4])

[1 2 3 4]


In [34]:
#Negative Slicing

print(Arr[-3: -1])


[5 6]


In [35]:
# step: using the step value to determine the step of the slicing

#Return every other element from index 1 to index 5:

print(Arr[1:5:2])

[2 4]


In [36]:
# return every other element from the entire array:
print(Arr[::2])

[1 3 5 7]


In [39]:
#Slicing 2-D arrays

#From the second element, slice elements from index 1 to index 4 (not included):
Arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(Arr2[1,1:4])

[7 8 9]


In [40]:
#From both elements, return index 2:
print(Arr2[0:2 ,2])


[3 8]


# Array Broadcasting

In [41]:
macros=np.array([[0.8,2.9,3.9],
               [52.4,23.6,36.5],
               [55.2,31.7,23.9],
                 [14.4,11,4.9]
                ])
calpermacro=np.array([3,3,8])
result=macros *calpermacro
print(result)

[[  2.4   8.7  31.2]
 [157.2  70.8 292. ]
 [165.6  95.1 191.2]
 [ 43.2  33.   39.2]]


In [42]:
x=np.array([1.0,2.0,3.0])
y=np.array([2.0,2.0,2.0])
z=x*y
print(z)

[2. 4. 6.]


In [43]:
zc=y*x
print(zc)

[2. 4. 6.]


In [45]:
s=2.0
zs=x*s
print(zs)

[2. 4. 6.]
